import type { Metadata } from "next";
// import "./globals.css";
import { ApiProvider } from "@/src/context/ApiProvider";
import { RestoreScrollProvider } from "@/src/context/RestoreScrollProvider";
import { Asset360Provider } from "@/src/context/Asset360Provider";
import { montserrat } from "./font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ApiProvider>
            <RestoreScrollProvider>
                <Asset360Provider>
                    <html lang="en">
                        <body className={montserrat.className}>{children}</body>
                    </html>
                </Asset360Provider>
            </RestoreScrollProvider>
        </ApiProvider>
    );
}
